### PR TITLE
Fix config

### PR DESCRIPTION
**Pull request by stilic**

### CODE REVIEW

**Comment by samuelscheit** [comment]
what exactly did you fix?

**Comment by stilic** [comment]
The webpack config

**Comment by samuelscheit** [comment]
Elaborate, what was the issue?

**Comment by stilic** [comment]
When I have try to start the client, he have show a error about the `webpack.config.js` file. I have copy-pasted the content of the file on github before the @jhcpeixoto commit and the issue was fixed.

**Pull request merged**
