### PR TITLE
UPDATES

### PR DESCRIPTION
**Pull request by jhcpeixoto**

### CODE REVIEW

**Comment by xnacly** [comment]
Please describe the changes you made, and create smaller per change commits.
Also please describe the changes in the commit itself.

**Comment by jhcpeixoto** [comment]
**UPDATES** 
- SIDE BAR
- GUILD CONTAINER
- SOME CSS FIXS

**Comment by samuelscheit** [comment]
is your caps lock broken or why are you writing everything in caps 😂

**Comment by jhcpeixoto** [comment]
Hahahahh sorry caps

**Pull request merged**
