### PR TITLE
add menu

### PR DESCRIPTION
**Pull request by stilic**

### CODE REVIEW

**Comment by stilic** [comment]
image

**Comment by stilic** [comment]
image

**Comment by stilic** [comment]
image

**Comment by xnacly** [comment]
Honestly the menu doesn't look good, please don't add that. 
Try to make it similar to discord.

**Comment by stilic** [comment]
we could use live share for do it at two guys

**Comment by xnacly** [comment]
I don't understand the usecase for that button. Why would we need that.
If a user wants to access the channels he can swipe to the left. If a user wants to access a channel he can press the channel. So what is the need for this button?

**Comment by stilic** [comment]
some apps don't allow users to swipe
these users need to click on a button like this button for reveal menu

**Comment by xnacly** [comment]
Huh? What are you talking about?
The button your are trying to add should be in the top left of the channels Toolbar like so: image

**Comment by stilic** [comment]
for really do this, we need to fusion sidebar and guildsidebar files contents
but i will need help for do this

**Comment by jhcpeixoto** [comment]
I can do this

**Comment by stilic** [comment]
ok
cool

**Pull request closed without merging**
